apiVersion: batch/v1
kind: Job
metadata:
  name: fraud-feature-engineering-job
  namespace: mlops
  labels:
    app: fraud-detection
    step: feature-engineering
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: fraud-detection
        step: feature-engineering
    spec:
      restartPolicy: Never
      containers:
        - name: feature-engineering
          image: ghcr.io/getaway001/fraud-detection-mlops:latest
          imagePullPolicy: Always   # toujours retélécharger la dernière image publiée par le CI/CD
          command: ["python", "-m", "src.features.build_features"]
          env:
            - name: RAW_DATA_PATH
              value: "/app/data/raw/Fraud_Detection_Dataset.csv"
            - name: PROCESSED_DIR
              value: "/app/data/processed"
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: fraud-data-pvc